# Generated by Django 5.2.4 on 2025-07-18 00:28

import comerciantes.models
import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre oficial o comercial del negocio.', max_length=200)),
                ('what_they_sell', models.TextField(help_text='Descripción de los productos o servicios que ofrece el negocio.')),
                ('hours', models.CharField(help_text="Horario de atención del negocio (ej. 'Lun-Vie: 9am-6pm').", max_length=255)),
                ('municipality', models.CharField(choices=[('Uriangato', 'Uriangato'), ('Moroleon', 'Moroleón'), ('Salamanca', 'Salamanca')], help_text='Municipio donde se encuentra el negocio.', max_length=100)),
                ('street_address', models.CharField(help_text='Dirección física completa del negocio.', max_length=255)),
                ('location_type', models.CharField(choices=[('Physical Store', 'Tienda Física'), ('Online Store', 'Tienda Online'), ('Market Stall', 'Puesto de Mercado'), ('Home Delivery', 'Solo a Domicilio')], help_text='Tipo de ubicación del negocio (ej. Tienda Física, Online, Puesto).', max_length=50)),
                ('contact_phone', models.CharField(blank=True, help_text='Número de teléfono de contacto del negocio (opcional).', max_length=20, null=True)),
                ('social_media_facebook_username', models.CharField(blank=True, help_text='Nombre de usuario de Facebook (opcional).', max_length=100, null=True)),
                ('social_media_instagram_username', models.CharField(blank=True, help_text='Nombre de usuario de Instagram (opcional).', max_length=100, null=True)),
                ('social_media_twitter_username', models.CharField(blank=True, help_text='Nombre de usuario de Twitter (opcional).', max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logotipo del negocio.', null=True, upload_to='business_logos/')),
                ('business_type', models.CharField(blank=True, choices=[('Food & Beverage', 'Alimentos y Bebidas'), ('Retail', 'Venta al por Menor'), ('Services', 'Servicios'), ('Crafts', 'Artesanía'), ('Agriculture', 'Agricultura')], help_text='Categoría o tipo de negocio (ej. Restaurante, Ropa, Servicios).', max_length=100, null=True)),
                ('is_paid_member', models.BooleanField(default=False, help_text='Indica si el negocio es un miembro de pago.')),
                ('membership_expires_at', models.DateTimeField(blank=True, help_text='Fecha y hora de expiración de la membresía.', null=True)),
                ('last_payment_date', models.DateField(blank=True, help_text='Fecha del último pago de la membresía.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Usuario asociado a este negocio.', on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Título breve y atractivo de la oferta (ej. 'Descuento 20% en pizzas').", max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada de la oferta, incluyendo qué se ofrece, condiciones, etc.')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Precio original del producto/servicio antes de aplicar el descuento (opcional).', max_digits=10, null=True)),
                ('discount_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio con descuento o precio final de la oferta.', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Imagen representativa de la oferta (opcional).', null=True, upload_to='offers_images/')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='Fecha a partir de la cual la oferta es válida.')),
                ('end_date', models.DateField(default=comerciantes.models.default_end_date, help_text='Fecha hasta la cual la oferta es válida.')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la oferta está activa y visible para los usuarios.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='El negocio que publica esta oferta.', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='comerciantes.business')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
