# Generated by Django 5.2.4 on 2025-07-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerciantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, choices=[('ROPA_MAYOREO_MENUDEO', 'Tiendas de Ropa al Mayoreo/Menudeo'), ('TALLERES_CONFECCION', 'Talleres de Confección'), ('TELAS_INSUMOS', 'Tiendas de Telas e Insumos Textiles'), ('MERCERIAS', 'Mercerías'), ('CALZADO', 'Calzado'), ('ABARROTES', 'Abarrotes'), ('TORTILLERIAS', 'Tortillerías'), ('CARNICERIAS', 'Carnicerías'), ('FRUTERIAS_VERDULERIAS', 'Fruterías y Verdulerías'), ('PANADERIAS', 'Panaderías'), ('FONDAS_COCINAS', 'Fondas/Cocinas Económicas'), ('TAQUERIAS_ANTOJITOS', 'Taquerías/Antojitos'), ('ESTETICAS', 'Estéticas'), ('PELUQUERIAS_BARBERIAS', 'Peluquerías/Barberías'), ('FARMACIAS', 'Farmacias'), ('PAPELERIAS_CIBER', 'Papelerías/Ciber-cafés'), ('TLAPALERIAS_FERRETERIAS', 'Tlapalerías/Ferreterías'), ('REFACCIONARIAS', 'Refaccionarias'), ('TALLERES_MECANICOS', 'Talleres Mecánicos'), ('VULCANIZADORAS', 'Vulcanizadoras'), ('VETERINARIAS', 'Veterinarias'), ('FLORISTERIAS', 'Floristerías'), ('JOYERIAS', 'Joyerías'), ('TIENDAS_REGALOS', 'Tiendas de Regalos'), ('LAVANDERIAS', 'Lavanderías'), ('MUEBLERIAS', 'Mueblerías'), ('TIENDAS_ELECTRONICA', 'Tiendas de Electrónica'), ('DULCERIAS', 'Dulcerías'), ('AGENCIAS_VIAJES', 'Agencias de Viajes'), ('ZAPATERIAS', 'Zapaterías')], help_text='Categoría o tipo de negocio (ej. Restaurante, Ropa, Servicios).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='location_type',
            field=models.CharField(choices=[('PLAZA_TEXTIL', 'Plaza Textil'), ('TIANGUIS', 'Tianguis'), ('MERCADO', 'Mercado'), ('LOCAL_CALLE', 'Local a la Calle'), ('ONLINE', 'Solo Online (sin ubicación física)'), ('OTRO', 'Otro')], help_text='Tipo de ubicación del negocio (ej. Tienda Física, Online, Puesto).', max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='municipality',
            field=models.CharField(choices=[('URIANGATO', 'Uriangato'), ('MOROLEON', 'Moroleón')], help_text='Municipio donde se encuentra el negocio.', max_length=100),
        ),
    ]
