# Generated by Django 5.2.4 on 2025-07-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerciantes', '0002_alter_business_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(blank=True, choices=[('ROPA_MAYOREO_MENUDEO', 'Tiendas de Ropa al Mayoreo/Menudeo'), ('TALLERES_CONFECCION', 'Talleres de Confección'), ('TELAS_INSUMOS', 'Tiendas de Telas e Insumos Textiles'), ('MERCERIAS', 'Mercerías'), ('CALZADO', 'Calzado'), ('ABARROTES', 'Abarrotes'), ('TORTILLERIAS', 'Tortillerías'), ('CARNICERIAS', 'Carnicerías'), ('FRUTERIAS_VERDULERIAS', 'Fruterías y Verdulerías'), ('PANADERIAS', 'Panaderías'), ('FONDAS_COCINAS', 'Fondas/Cocinas Económicas'), ('TAQUERIAS_ANTOJITOS', 'Taquerías/Antojitos'), ('ESTETICAS', 'Estéticas'), ('PELUQUERIAS_BARBERIAS', 'Peluquerías/Barberías'), ('FARMACIAS', 'Farmacias'), ('PAPELERIAS_CIBER', 'Papelerías/Ciber-cafés'), ('TLAPALERIAS_FERRETERIAS', 'Tlapalerías/Ferreterías'), ('REFACCIONARIAS', 'Refaccionarias'), ('TALLERES_MECANICOS', 'Talleres Mecánicos'), ('VULCANIZADORAS', 'Vulcanizadoras'), ('VETERINARIAS', 'Veterinarias'), ('FLORISTERIAS', 'Floristerías'), ('JOYERIAS', 'Joyerías'), ('TIENDAS_REGALOS', 'Tiendas de Regalos'), ('LAVANDERIAS', 'Lavanderías'), ('MUEBLERIAS', 'Mueblerías'), ('TIENDAS_ELECTRONICA', 'Tiendas de Electrónica'), ('DULCERIAS', 'Dulcerías'), ('AGENCIAS_VIAJES', 'Agencias de Viajes'), ('ZAPATERIAS', 'Zapaterías'), ('ARTESANIAS', 'Artesanías y Productos Típicos'), ('SERVICIOS_GENERALES', 'Servicios Generales (ej. reparaciones, cerrajería)'), ('PRODUCTOS_VARIOS', 'Productos Varios / Chácharas'), ('OTROS', 'Otros')], help_text='Categoría o tipo de negocio (ej. Restaurante, Ropa, Servicios).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='municipality',
            field=models.CharField(choices=[('ABASOLO', 'Abasolo'), ('ACAMBARO', 'Acámbaro'), ('ALLENDE', 'San Miguel de Allende'), ('APASEO_EL_ALTO', 'Apaseo el Alto'), ('APASEO_EL_GRANDE', 'Apaseo el Grande'), ('ATARJEA', 'Atarjea'), ('CELAYA', 'Celaya'), ('MANUEL_DOBLADO', 'Manuel Doblado'), ('COMONFORT', 'Comonfort'), ('CORONEO', 'Coroneo'), ('CORTAZAR', 'Cortazar'), ('CUERAMARO', 'Cuerámaro'), ('DOCTOR_MORA', 'Doctor Mora'), ('DOLORES_HIDALGO', 'Dolores Hidalgo Cuna de la Independencia Nacional'), ('GUANAJUATO', 'Guanajuato'), ('HUANIMARO', 'Huanímaro'), ('IRAPUATO', 'Irapuato'), ('JARAL_DEL_PROGRESO', 'Jaral del Progreso'), ('JERECUARO', 'Jerécuaro'), ('LEON', 'León'), ('MOROLEON', 'Moroleón'), ('OCAMPO', 'Ocampo'), ('OJITOS_DE_JAUREGUI', 'Ojo de Agua de Latillas'), ('PENJAMO', 'Pénjamo'), ('PUEBLO_NUEVO', 'Pueblo Nuevo'), ('PURISIMA_DEL_RINCON', 'Purísima del Rincón'), ('ROMITA', 'Romita'), ('SALAMANCA', 'Salamanca'), ('SALVATIERRA', 'Salvatierra'), ('SAN_DIEGO_DE_LA_UNION', 'San Diego de la Unión'), ('SAN_FELIPE', 'San Felipe'), ('SAN_FRANCISCO_DEL_RINCON', 'San Francisco del Rincón'), ('SAN_JOSE_ITURBIDE', 'San José Iturbide'), ('SAN_LUIS_DE_LA_PAZ', 'San Luis de la Paz'), ('SANTA_CATARINA', 'Santa Catarina'), ('SANTA_CRUZ_DE_JUVENTINO_ROSAS', 'Santa Cruz de Juventino Rosas'), ('SANTIAGO_MARAVATIO', 'Santiago Maravatío'), ('SILAO', 'Silao de la Victoria'), ('TARANDACUAO', 'Tarandacuao'), ('TARIMORO', 'Tarimoro'), ('TIERRA_BLANCA', 'Tierra Blanca'), ('URIANGATO', 'Uriangato'), ('VALLE_DE_SANTIAGO', 'Valle de Santiago'), ('VICTORIA', 'Victoria'), ('VILLAGRAN', 'Villagrán'), ('XICHU', 'Xichú'), ('YURIRIA', 'Yuriria')], help_text='Municipio donde se encuentra el negocio.', max_length=100),
        ),
    ]
