# Generated by Django 5.2.4 on 2025-07-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerciantes', '0003_alter_business_business_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='social_media_twitter_username',
        ),
        migrations.AddField(
            model_name='business',
            name='social_media_tiktok_username',
            field=models.CharField(blank=True, help_text='Nombre de usuario de TikTok (opcional).', max_length=100, null=True),
        ),
    ]
